/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 02-mai-2019 21:05:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS clientes_id_seq
;

DROP SEQUENCE IF EXISTS vendas_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS clientes CASCADE
;

DROP TABLE IF EXISTS despesas CASCADE
;

DROP TABLE IF EXISTS funcionarios CASCADE
;

DROP TABLE IF EXISTS tempo CASCADE
;

DROP TABLE IF EXISTS vendas CASCADE
;

/* Create Tables */

CREATE TABLE clientes
(
	cpf varchar(11) NOT NULL,
	nome varchar(50) NOT NULL,
	nome_cidade varchar(50) NOT NULL,
	uf varchar(50) NOT NULL,
	id integer NOT NULL   DEFAULT NEXTVAL(('"clientes_id_seq"'::text)::regclass)
)
;

CREATE TABLE despesas
(
	data_despesa date NOT NULL,
	valor numeric(10,2) NOT NULL,
	descricao varchar(50) NOT NULL,
	id integer NOT NULL
)
;

CREATE TABLE funcionarios
(
	cpf varchar(11) NOT NULL,
	nome varchar(50) NOT NULL,
	data_admissao date NOT NULL,
	data_demissao date NOT NULL,
	id integer NOT NULL
)
;

CREATE TABLE tempo
(
	id integer NOT NULL,
	ano integer NOT NULL,
	mes integer NOT NULL,
	nome_mes varchar(50) NOT NULL
)
;

CREATE TABLE vendas
(
	condicao_pagamento varchar(50) NOT NULL,
	forma_pagamento varchar(50) NOT NULL,
	valor numeric(10,2) NOT NULL,
	id integer NOT NULL   DEFAULT NEXTVAL(('"vendas_id_seq"'::text)::regclass),
	quantidade_itens integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE clientes ADD CONSTRAINT "PK_clientes"
	PRIMARY KEY (id)
;

ALTER TABLE despesas ADD CONSTRAINT "PK_despesas"
	PRIMARY KEY (id)
;

ALTER TABLE funcionarios ADD CONSTRAINT "PK_funcionarios"
	PRIMARY KEY (id)
;

ALTER TABLE tempo ADD CONSTRAINT "PK_tempo"
	PRIMARY KEY (id)
;

ALTER TABLE vendas ADD CONSTRAINT "PK_vendas"
	PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE despesas ADD CONSTRAINT "FK_despesas_tempo"
	FOREIGN KEY (id) REFERENCES tempo (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE vendas ADD CONSTRAINT "FK_vendas_funcionarios"
	FOREIGN KEY (id) REFERENCES funcionarios (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE vendas ADD CONSTRAINT "FK_vendas_tempo"
	FOREIGN KEY (id) REFERENCES tempo (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE clientes_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE vendas_id_seq INCREMENT 1 START 1
;
